"""Nomes de exibição (PT) para REF_AREA do BIS LONG CPI."""

from __future__ import annotations

AREA_NAMES: dict[str, str] = {
    "AE": "Emirados Arabes Unidos",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "BE": "Belgica",
    "BG": "Bulgaria",
    "BR": "Brasil",
    "CA": "Canada",
    "CH": "Suica",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "CY": "Chipre",
    "CZ": "Tchequia",
    "DE": "Alemanha",
    "DK": "Dinamarca",
    "DZ": "Argelia",
    "EE": "Estonia",
    "ES": "Espanha",
    "FI": "Finlandia",
    "FR": "Franca",
    "GB": "Reino Unido",
    "GR": "Grecia",
    "HK": "Hong Kong",
    "HR": "Croacia",
    "HU": "Hungria",
    "ID": "Indonesia",
    "IE": "Irlanda",
    "IL": "Israel",
    "IN": "India",
    "IS": "Islandia",
    "IT": "Italia",
    "JP": "Japao",
    "KR": "Coreia",
    "KW": "Kuwait",
    "LT": "Lituania",
    "LU": "Luxemburgo",
    "LV": "Letonia",
    "MA": "Marrocos",
    "MK": "Macedonia do Norte",
    "MT": "Malta",
    "MX": "Mexico",
    "MY": "Malasia",
    "NL": "Paises Baixos",
    "NO": "Noruega",
    "NZ": "Nova Zelandia",
    "PE": "Peru",
    "PH": "Filipinas",
    "PL": "Polonia",
    "PT": "Portugal",
    "RO": "Romenia",
    "RS": "Servia",
    "RU": "Russia",
    "SA": "Arabia Saudita",
    "SE": "Suecia",
    "SG": "Singapura",
    "SI": "Eslovenia",
    "SK": "Eslovaquia",
    "TH": "Tailandia",
    "TR": "Turquia",
    "US": "Estados Unidos",
    "XM": "Zona do Euro",
    "ZA": "Africa do Sul",
}


def display_name(code: str, fallback: str = "") -> str:
    c = (code or "").strip().upper()
    return AREA_NAMES.get(c) or fallback or c
